Colorful Universe Library/Controllers/WritersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Colorful_Universe_Library.Models.Entity;

namespace Colorful_Universe_Library.Controllers
{
    public class WritersController : Controller
    {
        // GET: Writers
        DBKUTUPHANEEntities2 db = new DBKUTUPHANEEntities2();
        public ActionResult Index()
        {
            var writer = db.TBLYAZAR.ToList();
            return View(writer);
        }

        [HttpGet]
        public ActionResult AddWriter()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddWriter(TBLYAZAR y)
        {
            var wrt = db.TBLYAZAR.Add(y);
            db.SaveChanges();
            return View();

        }

        public ActionResult DeleteWriter(int id)
        {
            var wrt = db.TBLYAZAR.Find(id);
            db.TBLYAZAR.Remove(wrt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ComeWriter(int id)
        {
            var wrt = db.TBLYAZAR.Find(id);
            return View("ComeWriter", wrt);
        }

        public ActionResult UpdateWriter(TBLYAZAR z)
        {
            var wrt = db.TBLYAZAR.Find(z.ID);
            wrt.AD = z.AD;
            wrt.SOYAD = z.SOYAD;
            wrt.DETAY = z.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Colorful Universe Library/Views/Writers/AddWriter.cshtml
@model Colorful_Universe_Library.Models.Entity.TBLYAZAR 
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Writer's Name'</label>
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
    </div>

    <div style="margin-top:15px">
        <label>Writer's Surname'</label>
        @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
    </div>

    <div style="margin-top:15px">
        <label>Detail'</label>
        @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control" })
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-warning">ADD WRITER</button>
    </div>

</form>

Colorful Universe Library/Views/Writers/ComeWriter.cshtml
@model Colorful_Universe_Library.Models.Entity.TBLYAZAR
@{
    ViewBag.Title = "ComeWriter";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("UpdateWriter", "Writers", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>

    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Writer's Name</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
        <br />
        <label>Writer's Surname</label>
        @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control" })
        <br />
        <label>Details</label>
        @Html.TextAreaFor(k => k.DETAY, new { @class = "form-control" })
        <br />
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-warning">Update</button>
    </div>
}

Colorful Universe Library/Views/Writers/Index.cshtml
@using Colorful_Universe_Library.Models.Entity
@model List<TBLYAZAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>WRITERS</h2>

<table class="table table-bordered">
    <tr>
        <th>Writer ID</th>
        <th>Writer's Name</th>
        <th>Writer's Surname</th>
        <th>Details</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (var wrt in Model)
    {
<tr>
    <td> @wrt.ID </td>
    <td> @wrt.AD </td>
    <td> @wrt.SOYAD </td>
    <td>@wrt.DETAY</td>
    <td> @Html.ActionLink("DELETE", "DeleteWriter", new { id = wrt.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Do you want to delete?')" })</td>
    <td> <a class="btn btn-danger" href="/Writers/ComeWriter/@wrt.ID">UPDATE</a> </td>

</tr>
    }

</table>

<a class="btn btn-primary" style="margin-bottom:20px" href="/Writers/AddWriter">WRITER ADD</a>