Colorful Universe Library/Controllers/PersonnelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Colorful_Universe_Library.Models.Entity;

namespace Colorful_Universe_Library.Controllers
{
    public class PersonnelController : Controller
    {
        // GET: Personnel

        DBKUTUPHANEEntities2 db = new DBKUTUPHANEEntities2();
        public ActionResult Index()
        {
            var pr = db.TBLPERSONEL.ToList();
            return View(pr);
        }

        [HttpPost]
        public ActionResult AddPersonnel(TBLPERSONEL p)
        {

            if (!ModelState.IsValid)
            {
                return View("AddPersonnel");
            }
            var pr1 = db.TBLPERSONEL.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]

        public ActionResult AddPersonnel()
        {
            return View();
        }


        public ActionResult DeletePersonnel(int id)
        {
            var pr2 = db.TBLPERSONEL.Find(id);
            db.TBLPERSONEL.Remove(pr2);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ComePersonnel(int id)
        {
            var pr3 = db.TBLPERSONEL.Find(id);
            return View("ComePersonnel", pr3);
        }

        public ActionResult UpdatePersonnel(TBLPERSONEL p)
        {
            var pr4 = db.TBLPERSONEL.Find(p.ID);
            pr4.PERSONEL = p.PERSONEL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Colorful Universe Library/Views/Personnel/AddPersonnel.cshtml
@model Colorful_Universe_Library.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "AddPersonnel";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>ADD PERSONNEL</h2>

<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Personnel's Name</label>
        @Html.TextBoxFor(a => a.PERSONEL, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.PERSONEL, "", new { @style ="color:red" })
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-warning">ADD PERSONNEL</button>
    </div>
</form>

Colorful Universe Library/Views/Personnel/ComePersonnel.cshtml
@model Colorful_Universe_Library.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "ComePersonnel";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>UPDATE PERSONNEL</h2>

@using (Html.BeginForm("UpdatePersonnel", "Personnel", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>

    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Writer's Name</label>
        @Html.TextBoxFor(k => k.PERSONEL, new { @class = "form-control" })
        <br />
        
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-warning">Update</button>
    </div>
}

Colorful Universe Library/Views/Personnel/Index.cshtml
@using Colorful_Universe_Library.Models.Entity
@model List<TBLPERSONEL>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>PERSONNEL PAGE</h2>



<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Personnel's Name</th>    
        <th>DELETE</th>
        <th>UPDATE</th>
    </tr>

    @foreach (var personnel in Model)
    {
        <tr>
            <td>@personnel.ID</td>
            <td>@personnel.PERSONEL</td>            
            <td>@Html.ActionLink("DELETE", "DeletePersonnel", new { id = personnel.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Do you want to delete')" }) </td>
            <td><a class="btn btn-warning" href="/Personnel/ComePersonnel/@personnel.ID">UPDATE</a></td>

        </tr>
    }
</table>
<a class="btn btn-primary" style="margin-bottom:20px" href="/Personnel/AddPersonnel">PERSONNEL ADD</a>